{
  "formatVersion": "1.1",
  "component": {
    "group": "btw.community.gradle",
    "module": "btw-gradle-plugin",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "btw-gradle-plugin-0.1.0.jar",
          "url": "btw-gradle-plugin-0.1.0.jar",
          "size": 314792,
          "sha512": "bc879d038aac7ec9b42c42481d4b2691b0fd917e4f79e774921bbc13cf70298748e572623a89730d7abaf04a87f1eba8dc165095cdff7f060ef2a377125b5f43",
          "sha256": "c3d2e48b1ee6493c265583bf82135f794e36fee41f10747b35602c6d6c279616",
          "sha1": "531e07edb4739e8ddeaeabaaa3482e0717e455af",
          "md5": "d18da0fe981e9d0dfd5114498070af5d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.cloudbees",
          "module": "diff4j",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "io.sigpipe",
          "module": "jbsdiff",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "btw-gradle-plugin-0.1.0.jar",
          "url": "btw-gradle-plugin-0.1.0.jar",
          "size": 314792,
          "sha512": "bc879d038aac7ec9b42c42481d4b2691b0fd917e4f79e774921bbc13cf70298748e572623a89730d7abaf04a87f1eba8dc165095cdff7f060ef2a377125b5f43",
          "sha256": "c3d2e48b1ee6493c265583bf82135f794e36fee41f10747b35602c6d6c279616",
          "sha1": "531e07edb4739e8ddeaeabaaa3482e0717e455af",
          "md5": "d18da0fe981e9d0dfd5114498070af5d"
        }
      ]
    }
  ]
}
