{
  "formatVersion": "1.1",
  "component": {
    "group": "btw.community.gradle",
    "module": "btw-gradle-plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "btw-gradle-plugin-1.0.0.jar",
          "url": "btw-gradle-plugin-1.0.0.jar",
          "size": 335375,
          "sha512": "4831c7f17026073ebb1138de2a7686732fbd3e17bbae5e6d96b645b585735b0f3e38975856e3c4bcf955f57ad0405b9e7ae9770fe1103399011f899c6807de66",
          "sha256": "4668a7b769724b2f80c44aad099da0ba87f17c738b0ecfaa5ebecc1d0f05ea97",
          "sha1": "07ea2a364208424f7f3e67bd22e9c7323db1bdac",
          "md5": "7252cd928af10f2eded7ddfdb39b74cc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.cloudbees",
          "module": "diff4j",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "io.sigpipe",
          "module": "jbsdiff",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "btw-gradle-plugin-1.0.0.jar",
          "url": "btw-gradle-plugin-1.0.0.jar",
          "size": 335375,
          "sha512": "4831c7f17026073ebb1138de2a7686732fbd3e17bbae5e6d96b645b585735b0f3e38975856e3c4bcf955f57ad0405b9e7ae9770fe1103399011f899c6807de66",
          "sha256": "4668a7b769724b2f80c44aad099da0ba87f17c738b0ecfaa5ebecc1d0f05ea97",
          "sha1": "07ea2a364208424f7f3e67bd22e9c7323db1bdac",
          "md5": "7252cd928af10f2eded7ddfdb39b74cc"
        }
      ]
    }
  ]
}
