{
  "formatVersion": "1.1",
  "component": {
    "group": "btw.community.gradle",
    "module": "btw-gradle-plugin",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "btw-gradle-plugin-1.0.3.jar",
          "url": "btw-gradle-plugin-1.0.3.jar",
          "size": 348622,
          "sha512": "90755306301f4d01627685c55db57767eefc47a0c9c1144a05dd047b46f2b14dd2054bc85c30ead230e429eee15a93a875b95abf83084e82034c01ba763d5f60",
          "sha256": "89bec5249f4ba6d7c97606e9decde779a15159de52241f9ed708bcbb257690a1",
          "sha1": "bbfa69d3bff34805b74c18d1683197de0864cd46",
          "md5": "4627031435764c04165b7f67a41eb67f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.cloudbees",
          "module": "diff4j",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "io.sigpipe",
          "module": "jbsdiff",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "btw-gradle-plugin-1.0.3.jar",
          "url": "btw-gradle-plugin-1.0.3.jar",
          "size": 348622,
          "sha512": "90755306301f4d01627685c55db57767eefc47a0c9c1144a05dd047b46f2b14dd2054bc85c30ead230e429eee15a93a875b95abf83084e82034c01ba763d5f60",
          "sha256": "89bec5249f4ba6d7c97606e9decde779a15159de52241f9ed708bcbb257690a1",
          "sha1": "bbfa69d3bff34805b74c18d1683197de0864cd46",
          "md5": "4627031435764c04165b7f67a41eb67f"
        }
      ]
    }
  ]
}
