{
  "formatVersion": "1.1",
  "component": {
    "group": "btw.community.gradle",
    "module": "btw-gradle-plugin",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "btw-gradle-plugin-1.0.1.jar",
          "url": "btw-gradle-plugin-1.0.1.jar",
          "size": 335456,
          "sha512": "749b0ef007df9c37aa95af7296a62fba975179b30576f54e33187a36748fe98000d998691d10d61c969f397567ef0c2fe9477009238891ba7de6a19bdb774658",
          "sha256": "54fe1f1eefe4f41b9c1dee813514b6e1bfae06835d5cd334ecdbcfd23fb0cc6d",
          "sha1": "9a9caafd5ee521b35c65a2fa06f70dfb3378550b",
          "md5": "19661dec26c50847e40a923056c14381"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.cloudbees",
          "module": "diff4j",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "io.sigpipe",
          "module": "jbsdiff",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "btw-gradle-plugin-1.0.1.jar",
          "url": "btw-gradle-plugin-1.0.1.jar",
          "size": 335456,
          "sha512": "749b0ef007df9c37aa95af7296a62fba975179b30576f54e33187a36748fe98000d998691d10d61c969f397567ef0c2fe9477009238891ba7de6a19bdb774658",
          "sha256": "54fe1f1eefe4f41b9c1dee813514b6e1bfae06835d5cd334ecdbcfd23fb0cc6d",
          "sha1": "9a9caafd5ee521b35c65a2fa06f70dfb3378550b",
          "md5": "19661dec26c50847e40a923056c14381"
        }
      ]
    }
  ]
}
